name: build
on:
  push:
    paths-ignore:
    - "README.rst"
    - "doc/*"
    - "po/*"
  pull_request:
    paths-ignore:
    - "README.rst"
    - "doc/*"
    - "po/*"
  schedule:
    - cron: '0 7 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install the dependencies
      run: |
        # Install make dependencies
        sudo apt-get install pkg-config gettext libgtk-3-dev libsoup2.4-dev libconfig-dev libssl-dev libsecret-1-dev;
        # Install runtime dependencies
        sudo apt-get install glib-networking libgtk3.0 libsoup2.4 libconfig9 libsecret-1-0;
    - name: Build
      run: |
        ./configure \
        --prefix=/usr/local \
        --datadir=/usr/local/share \
        --sysconfdir=/etc;
        make;
    - name: Install
      run: |
        sudo make install;
        /bin/sh -c "/usr/local/bin/srain --version";
